path: favicons
tags:
  - '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">'
  - '<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">'
  - '<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">'
  - '<link rel="manifest" href="/manifest.json">'
  - '<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#333e48">'
  - '<meta name="apple-mobile-web-app-title" content="RightAsRain">'
  - '<meta name="application-name" content="RightAsRain">'
  - '<meta name="theme-color" content="#ffffff">'
remove_default: 1
_core:
  default_config_hash: HwbPAleld8fGYWEBocmgnJpHIFH5k4-fdA0eRR2nMKU
