module:
  acquia_contenthub: 0
  acquia_contenthub_subscriber: 0
  acquia_lift: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  duration_field: 0
  editor: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_media: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  lightning_roles: 0
  lightning_search: 0
  lightning_workflow: 0
  link: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  rest: 0
  robotstxt: 0
  scheduled_updates: 0
  search_api: 0
  search_api_db: 0
  search_api_views_taxonomy: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  views_taxonomy_term_name_depth: 0
  views_templates: 0
  views_ui: 0
  workbench_moderation: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  lightning: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
