unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: true
log: true
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  contact_message_sitewide_form: false
  node_article_form: false
  node_award_form: false
  node_bookshelf_form: false
  node_calendar_event_form: false
  node_campaign_form: false
  node_event_form: false
  node_event_location_form: false
  node_gallery_form: false
  node_landing_page_form: false
  node_page_form: false
  node_question_form: false
  node_webform_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
