button_option: stbc_custom
comments: 0
late_load: 0
location: block
node_types:
  article: article
  page: page
  award: null
  campaign: null
  event: null
  gallery: null
  landing_page: null
  question: null
  webform: null
option_extras:
  'Google Plus One:plusone': '0'
  'Facebook Like:fblike': '0'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Facebook:facebook'',''Twitter:twitter'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page:
    full: full
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  award:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  campaign:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  event:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  gallery:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  landing_page:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  question:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  webform:
    diff: '0'
    featured: '0'
    featured_content_2: '0'
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-558f1231-ff84-f783-9530-346b954c1c2e
callesi: '0'
