module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_update: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  disqus: 0
  editor: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_media: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  link: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  paragraphs: 0
  path: 0
  poll: 0
  quickedit: 0
  scheduled_updates: 0
  search: 0
  seckit: 0
  sharethis: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  uwmed_huddle_blocks: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workbench_moderation: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  lightning: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  uwmed_bootstrap: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
